# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-bluefin-custom
description: My custom Bluefin image with camera and firmware files
base-image: ghcr.io/ublue-os/bluefin
image-version: stable

modules:
  - type: copy
    files:
      - src: local/ov08x40.yaml
        dest: /usr/share/libcamera/ipa/simple/ov08x40.yaml
      - src: local/medid.bin
        dest: /usr/lib/firmware/edid/medid.bin

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
